app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

prices:
    type:     rest
    resource: AppBundle\Controller\PriceController

users:
    type:     rest
    resource: AppBundle\Controller\UserController

themes:
    type:     rest
    resource: AppBundle\Controller\ThemeController

preferences:
    type:     rest
    resource: AppBundle\Controller\PreferenceController